server:
  port: 9090

dtm:
  http-server: http://localhost:36789/api/dtmsvr
  sql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dtm_barrier
    username: root
    password: